test_cases = [
        "##Escape test",
        "#ai: one",
        "#name:rinima",
        "context1",
        "#watch: causion",
        "context2",
        "#end",
        "context3",
        "#ai: one again",
        "context4",
        "#see: two",
        "context5",
        "context5",
        "context5",
        "context5",
        "#end",
        "context6",
        "#ai:one again again",
        "context7",
        "#end",
        "context8",
        "context8",
        "context8",
        "context8",
        "context8",
        "context8",
        "#watch: do I need to watch?",
        "context9",
        "context9",
        "context9",
        "context9",
        "#watch: I am watching again",
        "context10",
        "context10",
        "context10",
        "#end",
        "context11",
        "context11",
        "context11",
        "#end",
        "context12",
        "context12",
]
